version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env
volumes:
  postgres-data:
